library(Rducks)

local({
  con <- DBI::dbConnect(duckdb::duckdb(config = list(allow_unsigned_extensions = "true")))
  on.exit(DBI::dbDisconnect(con, shutdown = TRUE), add = TRUE)
  rducks_enable(con, threads = "single")

  invisible(rducks_register_scalar_udf(con, "rducks_date", function(x) x + 1, "date", "date"))
  expect_equal(DBI::dbGetQuery(con, "SELECT rducks_date(DATE '2020-01-02') AS x")$x, as.Date("2020-01-03"))

  invisible(rducks_register_scalar_udf(con, "rducks_time", function(x) x + 1, "time", "time"))
  expect_equal(DBI::dbGetQuery(con, "SELECT CAST(rducks_time(TIME '01:02:03') AS VARCHAR) AS x")$x, "01:02:04")
  invisible(rducks_register_scalar_udf(con, "rducks_time_fraction", function() rducks_as_time("00:00:00.1234567"), character(), TIME))
  expect_equal(DBI::dbGetQuery(con, "SELECT CAST(rducks_time_fraction() AS VARCHAR) AS x")$x, "00:00:00.123457")
  invisible(rducks_register_scalar_udf(con, "rducks_time_bad", function() -1, character(), TIME))
  expect_error(DBI::dbGetQuery(con, "SELECT rducks_time_bad() AS x"), "Rducks")
  invisible(rducks_register_scalar_udf(con, "rducks_time_round_bad", function() 86399.9999996, character(), TIME))
  expect_error(DBI::dbGetQuery(con, "SELECT rducks_time_round_bad() AS x"), "Rducks")
  invisible(rducks_register_scalar_udf(con, "rducks_time_struct_fraction", function() list(t = rducks_as_time("00:00:00.1234567")), character(), STRUCT(t = TIME)))
  expect_equal(DBI::dbGetQuery(con, "SELECT CAST((rducks_time_struct_fraction()).t AS VARCHAR) AS x")$x, "00:00:00.123457")
  invisible(rducks_register_scalar_udf(con, "rducks_time_struct_bad", function() list(t = 86400), character(), STRUCT(t = TIME)))
  expect_error(DBI::dbGetQuery(con, "SELECT rducks_time_struct_bad() AS x"), "marshal")

  invisible(rducks_register_scalar_udf(con, "rducks_timestamp", function(x) x + 1, "timestamp", "timestamp"))
  expect_equal(DBI::dbGetQuery(con, "SELECT CAST(rducks_timestamp(TIMESTAMP '2020-01-02 03:04:05') AS VARCHAR) AS x")$x, "2020-01-02 03:04:06")
  invisible(rducks_register_scalar_udf(con, "rducks_timestamp_fraction", function() as.POSIXct("1970-01-01", tz = "UTC") + 0.1234567, character(), TIMESTAMP))
  expect_equal(DBI::dbGetQuery(con, "SELECT epoch_us(rducks_timestamp_fraction()) AS x")$x, 123457)
  invisible(rducks_register_scalar_udf(con, "rducks_timestamp_bad", function() 1e20, character(), TIMESTAMP))
  expect_error(DBI::dbGetQuery(con, "SELECT rducks_timestamp_bad() AS x"), "Rducks")
  invisible(rducks_register_scalar_udf(con, "rducks_timestamp_edge_bad", function() 9223372036854.775, character(), TIMESTAMP))
  expect_error(DBI::dbGetQuery(con, "SELECT rducks_timestamp_edge_bad() AS x"), "Rducks")
})
