if (requireNamespace("duckdb", quietly = TRUE) && requireNamespace("DBI", quietly = TRUE)) {
  con <- DBI::dbConnect(duckdb::duckdb(config = list(allow_unsigned_extensions = "true")), dbdir = ":memory:")
  on.exit(DBI::dbDisconnect(con, shutdown = TRUE), add = TRUE)
  expect_equal(NROW(rducks_list_udfs(con)), 0L)
  rducks_enable(con, threads = "single")
  native_fields <- Rducks:::rducks_native_udf_stat_fields(con)
  sql_fields <- strsplit(DBI::dbGetQuery(con, "SELECT rducks_udf_stat_fields() AS fields")$fields[[1L]], "\n", fixed = TRUE)[[1L]]
  expect_true("dispatch_chunks" %in% native_fields)
  expect_equal(native_fields, sql_fields)

  empty <- rducks_list_udfs(con)
  expect_equal(NROW(empty), 0L)
  expect_true("name" %in% names(empty))
  expect_true("r_side_record" %in% names(empty))

  invisible(rducks_register(con, "explain_plus_one", function(x) x + 1L, INTEGER, INTEGER))
  before <- rducks_explain_udf(con, "explain_plus_one")
  expect_true(before$r_side_record[[1L]])
  expect_equal(before$mode, "scalar")
  expect_equal(before$plan_id, "arrow_r+serial")
  expect_equal(before$native_marshalling, "arrow_r")
  expect_equal(before$dispatch_chunks, 0)
  expect_equal(before$arrow_r_chunks, 0)

  result <- DBI::dbGetQuery(con, "SELECT explain_plus_one(i::INTEGER) AS x FROM range(3) t(i)")
  expect_equal(result$x, 1:3)
  after <- rducks_explain_udf(con, "explain_plus_one")
  expect_equal(after$name, "explain_plus_one")
  expect_equal(after$args, "i32")
  expect_equal(after$returns, "i32")
  expect_equal(after$direct_chunks, after$dispatch_chunks)
  expect_equal(after$queued_chunks, 0)
  expect_equal(after$dispatch_rows, 3)
  expect_true(after$dispatch_chunks >= 1)
  expect_true(after$arrow_r_chunks >= 1)
  expect_equal(after$arrow_c_chunks, 0)

  rducks_set_execution_plan(con, rducks_execution_plan("arrow_c", "serial"))
  invisible(rducks_register(con, "explain_plus_two_c", function(x) x + 2L, INTEGER, INTEGER))
  result_c <- DBI::dbGetQuery(con, "SELECT explain_plus_two_c(i::INTEGER) AS x FROM range(4) t(i)")
  expect_equal(result_c$x, 2:5)
  after_c <- rducks_explain_udf(con, "explain_plus_two_c")
  expect_equal(after_c$plan_id, "arrow_c+serial")
  expect_equal(after_c$marshalling, "arrow_c")
  expect_equal(after_c$native_marshalling, "arrow_c")
  expect_true(after_c$arrow_c_chunks >= 1)
  expect_equal(after_c$arrow_r_chunks, 0)

  listed <- rducks_list_udfs(con)
  expect_equal(listed$name, c("explain_plus_one", "explain_plus_two_c"))
  expect_equal(listed$native_marshalling, c("arrow_r", "arrow_c"))
  expect_equal(listed$plan_id, c("arrow_r+serial", "arrow_c+serial"))
  expect_true(all(listed$r_side_record))
  expect_true(listed$dispatch_chunks[[1L]] >= 1)
  expect_true(listed$dispatch_chunks[[2L]] >= 1)

  expect_error(rducks_explain_udf(con, "missing_rducks_udf"), "unknown Rducks UDF")
}
